### ISSUE TITLE
Not possible to restart Dashing inside the container

### ISSUE THREAD

**Issue by emanuelef** [frvi/dockerfile-dashing#11]
Hi,
I'm trying to restart dashing from within the container, first I access the container using :

> docker exec -it 822bc5555a3c bash

But if I try to stop dashing I get an error:

```
root@822bc5555a3c:/dashing# dashing stop     
bundler: failed to load command: thin (/usr/local/bundle/bin/thin)
Thin::PidFileNotFound: Can't stop process, no PID found in tmp/pids/thin.pid
```

**Comment by frvi** [comment]
@emanuelef, this no longer an issue?

**Comment by emanuelef** [comment]
Hi,
now I'm running the container with -it so I can start stop dashing.
I was hoping to have 

> service dashing restart

But is not available. Also I was considering moving to Smashing as Dashing is no longer maintained.
